#!/bin/bash
cp /etc/postgresql/postgresql.conf /var/lib/postgresql/data/
cp /etc/postgresql/pg_hba.conf /var/lib/postgresql/data/
runuser -l postgres -c 'createuser admin'
runuser -l postgres -c 'psql < /var/createuser.sql'