#!/usr/bin/python3

__HELP__ = "Generate code for password renew"

from gaimon.util.PasswordRenewCodeGenerator import PasswordRenewCodeGenerator

import json, sys, os, asyncio, argparse

__parser__ = argparse.ArgumentParser(description=__HELP__)
__parser__.add_argument("-u", "--user", required=True, help="User ID to generate renew code.")
__parser__.add_argument("-e", "--expire", help="Number of days, in which the generate code will be expired. [DEFAULT=15 days]")
__option__ = __parser__.parse_args(sys.argv[1:])

async def __run__() :
	with open('/etc/gaimon/Database.json') as fd :
		config = {
			'DB' : json.load(fd)
		}
		generator = PasswordRenewCodeGenerator(config)
	await generator.connectDB()
	uid = int(__option__.user)
	expire = 15 if __option__.expire is None else int(__option__.expire)
	renew = await generator.generate(uid, expire)
	print(f"CODE : {renew.token.decode()}")

asyncio.run(__run__())