#!/usr/bin/python3

import os
import shutil
import argparse
from datetime import datetime

def copy_models_with_timestamp(root_folder):
    destination_folder = os.path.join(root_folder, "freeze-model")

    if not os.path.exists(destination_folder):
        os.makedirs(destination_folder)

    version = datetime.now().strftime("%Y/%m/04/%H:%M:%S")
    version_folder = os.path.join(destination_folder, f"{version}")
    os.makedirs(version_folder)

    for root, dirs, files in os.walk(root_folder):
        if "model" in dirs:
            module_name = os.path.basename(root)
            models_folder = os.path.join(root, "model")

            destination_module_folder = os.path.join(version_folder, module_name)
            if not os.path.exists(destination_module_folder):
                os.makedirs(destination_module_folder)

            for filename in os.listdir(models_folder):
                file_path = os.path.join(models_folder, filename)
                if os.path.isdir(file_path) or os.stat(file_path).st_size == 0:
                    continue
                if filename.endswith(".py"):
                    new_filename = filename[:-3] + ".txt"
                    destination_file_path = os.path.join(
                        destination_module_folder, new_filename
                    )
                    shutil.copy2(file_path, destination_file_path)
            print(
                f"Models from {module_name} copied successfully to {destination_module_folder}"
            )


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Process some integers.')
    parser.add_argument('folder_path', type=str, help='The path to the folder')
    args = parser.parse_args()
    copy_models_with_timestamp(args.folder_path)