#!/usr/bin/python3

from gaimon.util.ProcessUtil import readConfig, daemonize, setSystemPath

import sys, argparse

__parser__ = argparse.ArgumentParser(description="Gaimon Monitor server.")
__parser__.add_argument("-n", "--namespace", help="Namespace of monitor application.")
__parser__.add_argument("-d", "--daemon", help="Run in daemon mode.", choices=['start', 'stop', 'restart', 'kill'],)
__option__ = __parser__.parse_args(sys.argv[1:])
__namespace__ = '' if __option__.namespace is None else __option__.namespace
__config__ = readConfig(
	['Gaimon.json', 'ServiceMonitor.json'],
	{},
	__namespace__
)
from gaimon.service.monitor.MonitorService import MonitorService
if len(__namespace__) : setSystemPath(__namespace__)

__notification__ = MonitorService(__config__, __namespace__)

if __name__ == '__main__' :
	if  __option__.daemon :
		daemonize('gaimon-monitor', __option__.daemon, __notification__.run, '')
	else :
		__notification__.run()