const ViewType = {
	MAIN: 'MAIN',
	INSERT: 'INSERT',
	UPDATE: 'UPDATE',
	TABLE: 'TABLE',
	DETAIL: 'DETAIL',
	SUMMARY: 'SUMMARY',
	MAIN_DIALOG: 'MAIN_DIALOG',
	INSERT_DIALOG: 'INSERT_DIALOG',
	UPDATE_DIALOG: 'UPDATE_DIALOG',
	TABLE_DIALOG: 'TABLE_DIALOG',
	DETAIL_DIALOG: 'DETAIL_DIALOG',
	SUMMARY_DIALOG: 'SUMMARY_DIALOG',
};